### ISSUE TITLE
Make name of version.json endpoint configurable

### ISSUE THREAD

**Issue by amdprophet** [sensu/catalog-api#27]
In order to allow various methods of handling multiple catalog version endpoints. E.g. `production.json` and `staging.json` at the root of the S3 bucket. We can add a command line flag to control the name of the filename.

We may also want to consider renaming the default of `version.json` to `latest.json`, `production.json` or `stable.json`.

**Comment by calebhailey** [comment]
My vote is for `latest.json`

**Comment by jamesdphillips** [comment]
`latest` seems to match the convention in the Docker community? I'm for whatever is the most conventional.

**Comment by calebhailey** [comment]
@jamesdphillips if we all agree on this, should I go ahead and make an issue in sensu/sensu-enterprise-go to make this configurable via web/v1.WebConfig?

**Comment by jamesdphillips** [comment]
![](https://www.startrek.com/sites/default/files/images/2019-01/d7b431b1a0cc5f032399870ff4710743.jpeg)

**Comment by calebhailey** [comment]
I updated https://github.com/sensu/sensu-enterprise-go/issues/2071 to incorporate the URL and release/version.

**Comment by amdprophet** [comment]
Closed by https://github.com/sensu/catalog/pull/159.
